version: '3.4'

services:
  tasks:
    build:
      context: './'
    volumes:
      - './:/app:delegated'
      - 'tmp:/mnt/tmp'
    env_file: './.env'
    command: ["/bin/bash"]
    stdin_open: true
    tty: true

volumes:
  tmp:
